### ISSUE TITLE
per-library logging

### ISSUE THREAD

**Issue by beekhof** [ClusterLabs/libqb#133]
not sure how to make it work, but it would be cool if we could turn on logging 'per-library'

ie. I have this thing in sbd, where -v turns on SBD's logging, but -v -v turns on everyone's logs.

```
    case 'v':
               debug++;
               if(debug == 1) {
                   qb_log_filter_ctl(QB_LOG_SYSLOG, QB_LOG_FILTER_ADD, QB_LOG_FILTER_FILE, "sbd-common.c,sbd-inquisitor.c,sbd-md.c,sbd-pacemaker.c", LOG_DEBUG);
                   qb_log_filter_ctl(QB_LOG_STDERR, QB_LOG_FILTER_ADD, QB_LOG_FILTER_FILE, "sbd-common.c,sbd-inquisitor.c,sbd-md.c,sbd-pacemaker.c", LOG_DEBUG);
        cl_log(LOG_INFO, "Verbose mode enabled.");

               } else if(debug == 2) {
                   /* Go nuts, turn on pacemaker's logging too */
                   qb_log_filter_ctl(QB_LOG_SYSLOG, QB_LOG_FILTER_ADD, QB_LOG_FILTER_FILE, "*", LOG_DEBUG);
                   qb_log_filter_ctl(QB_LOG_STDERR, QB_LOG_FILTER_ADD, QB_LOG_FILTER_FILE, "*", LOG_DEBUG);
        cl_log(LOG_INFO, "Verbose library mode enabled.");
               }
               break;
```

Works but clunky, what you'd really want is something like:

  qb_log_filter_ctl(QB_LOG_SYSLOG, QB_LOG_FILTER_ADD, QB_LOG_FILTER_LIB, "local/none", LOG_DEBUG);
and
  qb_log_filter_ctl(QB_LOG_SYSLOG, QB_LOG_FILTER_ADD, QB_LOG_FILTER_LIB, "libpe_status", LOG_DEBUG);

**Comment by jnpkrn** [comment]
Looks like this is doable, either using `dladdr` extension of `<dlfcn.h>`
or some other hackery.  What I am afraid is that it will be too fragile
wrt. API/ABI and user expectations (i.e., will everything using libqb need
to be recompiled for this to work? etc.)

**Comment by jnpkrn** [comment]
In case just an arbitrary (but consistent) identification string is enough per
linked unit, `QB_LOG_INIT_DATA` might be used to set this association.
See also PR #196 (it wouldn't be wise to drop/NOOPize that prematurely),
for instance, Pacemaker uses that for its libraries.

**Comment by jnpkrn** [comment]
I've just run into the situation when enabling logging/tracing (externally from the environment, the same way as pacemaker does it for functions/files) for particular library would be handy.
