### ISSUE TITLE
autogen.sh fails with latest autoconf & automake

### ISSUE THREAD

**Issue by JVD66** [ClusterLabs/libqb#135]
The libqb project fails to build under an Ubuntu 14.04.1 LTS x86_64 linux system, either with the 
distro's automake-1.10.3 and autoconf-2.69 .  or with the autoconf-2.69 (latest version) and the 
latest 1.14.1 version of automake installed : 

automake-1.10.3 & autoconf-2.69 failure log:
 $ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
main::scan_file() called too early to check prototype at /usr/bin/aclocal line 616.
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
main::scan_file() called too early to check prototype at /usr/bin/aclocal line 616.
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:11: option `dist-xz' not recognized
autoreconf: automake failed with exit status: 1

automake-1.14.1 & autoconf-2.69 failure log:
$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
main::scan_file() called too early to check prototype at /usr/bin/aclocal line 616.
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
main::scan_file() called too early to check prototype at /usr/bin/aclocal line 616.
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:11: error: version mismatch.  This is Automake 1.14.1,
configure.ac:11: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:11: comes from Automake 1.10.3.  You should recreate
configure.ac:11: aclocal.m4 with aclocal and run automake again.
configure.ac:11: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:11: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:11: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:61: installing './compile'
configure.ac:18: installing './config.guess'
configure.ac:18: installing './config.sub'
configure.ac:11: installing './install-sh'
configure.ac:11: installing './missing'
examples/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
/usr/local/share/automake-1.14/am/check2.am: error: am__EXEEXT does not appear in AM_CONDITIONAL
/usr/local/share/automake-1.14/am/check2.am: error: am__EXEEXT does not appear in AM_CONDITIONAL
autoreconf: automake failed with exit status: 63

Please either:
o) Check-In a working configure script to the GIT repository;
o) Check in the versions of autoconf & automake that will cause autogen.sh to work to the GIT repository
o) Specify the exact versions of automake & autoconf that work for you in the INSTALL file.

 The problem is fixed by the patch:
$ diff -U0 configure.ac~ configure.ac
--- configure.ac~       2014-12-09 13:55:52.271893469 +0000
+++ configure.ac        2014-12-09 13:53:32.603163613 +0000
@@ -11 +11 @@
-AM_INIT_AUTOMAKE([-Wno-portability dist-xz color-tests parallel-tests])
+AM_INIT_AUTOMAKE([-Wno-portability])

Removing the offending 'dist-xz color-tests parallel-tests' macro invocations fixes the issue. 
Perhaps you should ship the definitions of these macros if you rely on them ?

**Comment by chrissie-c** [comment]
1.0rc1 was released with much newer automake version. Can you try it now and see this is fixed please?

**Comment by chrissie-c** [comment]
I'm going to close this in the assumption that, as we are now using newer automake/conf versions it should be fine.

**Comment by jnpkrn** [comment]
To be noted that travis CI jobs are currently using `Ubuntu 12.04.5 LTS`
and all works like a charm wrt. autotools:
https://travis-ci.org/ClusterLabs/libqb
