### ISSUE TITLE
git-version-gen error when buliding with release tarball

### ISSUE THREAD

**Issue by rikkotec** [ClusterLabs/libqb#145]
Hello,

When building from source - using a release tarball, there is no `.git` directory, and no stale `.tarball-version` file.

This causes `.version` to be generated with `UNKNOWN` as the version string, and effectively causes the version string in libqb*.pc to be UNKNOWN...which results in `pkg-config --modversion libqb` to fail.

**Comment by rikkotec** [comment]
Suggested fix:

Please pack a stale .tarball-version file in the release tarballs, so we can keep the source tarball pristine over @ debian-ha.

**Comment by rikkotec** [comment]
The suggested fix is still suggested, but I should correct myself:

We're not injecting the tarball with the .tarball-version file, rather we are patching to accommodate it not being there.

Best,

**Comment by chrissie-c** [comment]
The 0.17.2 tarball has a .tarball_version file in it

**Comment by fauno** [comment]
the ,tarball_version file is missing on 1.0.2 :)

**Comment by chrissie-c** [comment]
It's not in the github-provided archives, but they're not to be used. The .gz and .xz versions are the official, signed tarballs and they both have .tarball_version in. Annoyingly it seems impossible to stop github generating useless "Source Code" files :/

**Comment by fauno** [comment]
aaah i see, thanks!

-- 
:O

**Comment by chrissie-c** [comment]
I've made a note in the release text, so it's should be clear now. Sorry for the confusion.

**Comment by MarcinWieczorek** [comment]
What is the point of a PGP signed sha256 sums? It might not be unsecure, it's just not portable. I need to use a fixed sha256 sum and verify the tarball with PGP.

**Comment by chrissie-c** [comment]
Being honest .. I don' t know. I inherited the build system and I'm not a security expert so am reluctant to change it without someone, who knows what they're talking about, looking it over carefully.

**Comment by fabbione** [comment]
sha256 is still safe AFAIK, so as long as you can verify that the sha number is correct, and the tarball reports the same sha, then you should be good to go.

Anyway it´s also reasonable to sign the tarball directly, the change to the build system should be minimal.

**Comment by MarcinWieczorek** [comment]
It is fairly safe. IMHO there's no serious reason to change it, I couldn't have found one. I'm asking you to release signed tarballs just because everybody does it that way and I need it that way for my build script.

**Comment by chrissie-c** [comment]
Fair point. I've uploaded signatures for the 1.0.2 tarballs and added code to the release script to generate them in future.
