### ISSUE TITLE
.gitignore should not be in a release tarball file

### ISSUE THREAD

**Issue by rikkotec** [ClusterLabs/libqb#148]
The `.gitignore` file in the release tarball brings a need for package maintainers to patch the source in order to remove the `.gitignore` file.

It causes issues during automated build processes carried out by such tools as gbp.

**Comment by rikkotec** [comment]
An easy fix was to add another `.gitignore` to `debian/` directory, and adding `!libqb-*` as its directive.  That directive in the root ignore file is causing gbp not to carry over mission-critical `debian/*` files.

**Comment by chrissie-c** [comment]
.gitignore was not in the 0.17.2 tarball so closing this.

TBH I'm not entirely sure what changed - it was probably before I took over, I'll keen an eye on the next version
