### ISSUE TITLE
Call autogen.sh at built-time

### ISSUE THREAD

**Issue by rikkotec** [ClusterLabs/libqb#149]
Just a suggestion:

The normal user should not have to call autogen.sh, it would be awesome if it could be done prior to creating the release-tarball.

**Comment by sdake** [comment]
This is not how release tarballs are created.  We went through this whole debate/discussion during Corosync development 6-7 years ago for months, and the result was the user absolutely needs to run autogen.sh.

**Comment by rikkotec** [comment]
Alright, no disrespect meant at all - the DDs sponsoring me @ Debian suggested to mention this upstream; I'll let the know of the response.

**Comment by fabbione** [comment]
On 4/18/2015 1:28 AM, Steven Dake wrote:
> This is not how release tarballs are created. We went through this whole
> debate/discussion during Corosync development 6-7 years ago for months,
> and the result was the user absolutely needs to run autogen.sh.
> 

not in the release tarball no. autogen.sh is a developer tool. The
release tarball needs to ship a configure file that final user can use
directly.

**Comment by rikkotec** [comment]
@fabbione Yea that's what those @ Debian are saying too.

**Comment by fabbione** [comment]
On 4/20/2015 12:15 AM, Richard Winters wrote:
> @fabbione <https://github.com/fabbione> Yea that's what those @ Debian
> are saying too.

Yes I am aware. I am DD too :)

Fabio
