### ISSUE TITLE
No ChangeLog present in release tarball

### ISSUE THREAD

**Issue by rikkotec** [ClusterLabs/libqb#151]
Would it be possible to have the ChangeLog generated for the release tarballs?

I am able to generate them by cloning the repository and running (from the repository root) `./build-aux/gitlog-to-changelog > ChangeLog`.

However, having it in the Release Tarball from the get-go would be ideal me thinks; since at this point we have to patch the ChangeLog into the source for our builds :)

Best,

**Comment by davidvossel** [comment]
oops. guilty. I'll add that to my todo list for the next release.

**Comment by rikkotec** [comment]
On Mon, 2015-04-20 at 10:40 -0700, David Vossel wrote:
> oops. guilty. I'll add that to my todo list for the next release.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

Awesome, thank you :)

-- 
Rik

**Comment by wferi** [comment]
Maybe we just can't find the proper 0.17.1 release tarball. For example, https://fedorahosted.org/releases/q/u/quarterback/libqb-0.17.0.tar.gz contains a `ChangeLog` and a `.tarball-version` file as well (see #145). The archives created automatically for each tag by GitHub obviously don't contain such generated files, as those are created by the proper release process. I think it would be useful to document the distribution point more prominently (like in the `INSTALL` or the `README.markdown` file).

**Comment by wferi** [comment]
Thanks for releasing 0.17.2! Sadly, it still did not come in the form of a proper distribution tarball. The archives generated automatically by GitHub do not contain the `ChangeLog` and the `.tarball-version` files (and the Autoconf stuff `make dist` also adds). Missing `ChangeLog` is rather inconvenient, because it can't be generated from the snapshot tarballs. Also, `.tarball-version` is needed for building the pkg-config file, so it has to be added before packaging, but that could be automated.
Are you (libqb developers) interested in doing tarball releases, or should we (packagers) develop a long-term solution for generating `.tarball-version`? (Generating `ChangeLog` is not possible from the snapshot tarballs, so we'd probably have to drop that.)

**Comment by chrissie-c** [comment]
I think I'd like to produce a 'proper' tarball for packagers, if there are things missing from this release then put it down to the new maintainer (me) who had to rather peremptorily take over the job! I'll look into what needs to be done to get things good for you again.

**Comment by chrissie-c** [comment]
these should be good release tarballs: https://fedorahosted.org/releases/q/u/quarterback/

**Comment by wferi** [comment]
Thanks, @chrissie-c, they are great indeed! I could package them without any patching at all. I can see you published them on the GitHub release page as well. What will be the offical download location? I'd like to set up the watcher script accordingly.

**Comment by chrissie-c** [comment]
I'd like to retire fedorahosted as the official download location - it's an extra step in the release process for no real benefit. So from next time I'll just post to github. It's annoying that github insists on packaging the files from git so there will always be the two source archives on there but I think we'll have to live with that.

In short - set up a watcher on github and look for the version numbered tarballs (not the 'Source Code' ones). There will also be the sha256 hashes too.

**Comment by wferi** [comment]
Fine, thanks. I think this issue can be closed now.

**Comment by chrissie-c** [comment]
OK :)

**Comment by wferi** [comment]
Hello again! What happened to the 0.17.2 release on GitHub? The v0.17.2 tag is only 6 days old now, while it was certainly present 14 days ago. The release tarballs are also gone, I can only find the automatically generated archives now. Could you please fix this up?

**Comment by chrissie-c** [comment]
ARGH! Sorry, this is github being annoying - as it is so good at. We had to move the 0.17.2 tag for documentation reasons - nothing in the code is affected - it's to do with the website doc. I didn't realise that github would change the release status back to 'Draft'. I've re-published it and it should all be OK now. Sorry about that, and thank you for drawing it to my attention.
