### ISSUE TITLE
Typo in ipc_setup.c.

### ISSUE THREAD

**Issue by fskale** [ClusterLabs/libqb#156]
Hi,
only wanted to inform you, that there's a typo in function ipc_setup.c.
upg was no defined, but data ;-)
So, since i'm on solaris it will hit the bug.
Here's the patch:
```
--- lib/ipc_setup.c	Fri May 15 07:38:56 2015
+++ lib/ipc_setup.c	Fri May 15 07:39:59 2015
@@ -628,9 +628,9 @@

 		if (getpeerucred(data->sock, &uc) == 0) {
 			res = 0;
-			ugp.uid = ucred_geteuid(uc);
-			ugp.gid = ucred_getegid(uc);
-			ugp.pid = ucred_getpid(uc);
+			data->ugp.uid = ucred_geteuid(uc);
+			data->ugp.gid = ucred_getegid(uc);
+			data->ugp.pid = ucred_getpid(uc);
 			ucred_free(uc);
 		} else {
 			res = -errno;
@@ -645,7 +645,7 @@
 		 * TODO get the peer's pid.
 		 * c->pid = ?;
 		 */
-		if (getpeereid(data->sock, &ugp.uid, &ugp.gid) == 0) {
+		if (getpeereid(data->sock, &data->ugp.uid, &data->ugp.gid) == 0) {
 			res = 0;
 		} else {
 			res = -errno;
```

Rgds.

Franz

**Comment by davidvossel** [comment]
excellent, Thanks!

I created a pull request and will merge soon.
https://github.com/ClusterLabs/libqb/pull/157

I do a series of portability tests that catch this sort of thing. This was introduced recently and should not be in any official upstream releases.

**Comment by fskale** [comment]
Hi David,
i know, but i had troubles with 0.17 but then found the patches from Andreas Grüni, which fixed my problems with the stale socket files.
Before, i did a clone of the newest git version.
Fyi, this version doesn't work under Solaris, since it sets a scheduler prio, which Solaris doesn't allow. (priocntl).
But for me, the patched version works.

Rgds.
Franz

________________________________
Von: David Vossel [notifications@github.com]
Gesendet: Freitag, 15. Mai 2015 16:28
An: ClusterLabs/libqb
Cc: Skale Franz
Betreff: [MASSMAIL]Re: [libqb] Typo in ipc_setup.c. (#156)


excellent, Thanks!

I created a pull request and will merge soon.
#157<https://github.com/ClusterLabs/libqb/pull/157>

I do a series of portability tests that catch this sort of thing. This was introduced recently and should not be in any official upstream releases.

**Comment by chrissie-c** [comment]
Closing this because the patch has been pulled.
