### ISSUE TITLE
Building out-of-tree doesn't work

### ISSUE THREAD

**Issue by dkopecek** [ClusterLabs/libqb#158]
Hello. Out-of-tree building of libqb is currently broken. Steps to reproduce:
```
$ ./autogen.sh
$ mkdir _build && cd _build
$ ../configure
$ make
...
make[2]: Entering directory `/home/dkopecek/Projects/github/usbguard/src/ThirdParty/libqb/_build/tests'
...
  GEN      auto_check_header_qbarray.c
  CC       auto_check_header_qbarray.o
  CCLD     auto_check_header_qbarray
make[2]: *** No rule to make target `auto_check_header_qbconfig.c', needed by `auto_check_header_qbconfig.o'.  Stop.
make[2]: Leaving directory `/home/dkopecek/Projects/github/usbguard/src/ThirdParty/libqb/_build/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/dkopecek/Projects/github/usbguard/src/ThirdParty/libqb/_build'
make: *** [all] Error 2
```
The problem seems to be that the `auto_check_header_%.c` source file generating part of the makefile doesn't count with out-of-tree builds.

**Comment by dkopecek** [comment]
One year later, it still doesn't work.

**Comment by chrissie-c** [comment]
It's not a priority, and I'm no automake expert. If someone submits a patch I will happily consider it though.

**Comment by dkopecek** [comment]
Sorry, half year :D Anyway, good to have at least some reaction to this ticket. I'll see whether I could help to fix this.

**Comment by chrissie-c** [comment]
I did look at it when I was assessing what should go into the -rc but decided it needed more knowledge of automake that I was prepared to spend time on at the moment! Any help is appreciated, thanks :)

**Comment by chrissie-c** [comment]
That's great. Thanks a lot  - merged :)

**Comment by jnpkrn** [comment]
Accidentally noticed I subsequently broke out-of-tree building with
0b04ed5 (#184).

Restoring that ability: PR #200.
