### ISSUE TITLE
libqb FTBFS on debian mips/mipsel

### ISSUE THREAD

**Issue by aborrero** [ClusterLabs/libqb#165]
Hi!

It seems libqb FTBFS on debian mips/mipsel. The issue seems to be in the test-suite

Here are the build logs, which I believe include the tests/test-suite.log
 * [mipsel](https://buildd.debian.org/status/fetch.php?pkg=libqb&arch=mipsel&ver=0.17.2.real-2&stamp=1443004566)
 * [mips](https://buildd.debian.org/status/fetch.php?pkg=libqb&arch=mips&ver=0.17.2.real-2&stamp=1443010097)

Do you know how this issue can be addressed? Please note that I know nothing about the libqb codebase.

**Comment by chrissie-c** [comment]
This looks like a bug I fixed on Tuesday! Can you try with this commit applied please?

https://github.com/ClusterLabs/libqb/commit/1908e6c15b6e3acbf083189117b314c0791f016d

**Comment by ChristophBerg** [comment]
It doesn't seem to help on the mips box I just tried: Linux minkus 3.16.0-4-octeon #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) mips GNU/Linux

**Comment by chrissie-c** [comment]
OK, I think I see what's happening. Can you change the second one of those (line 676) back from 9  to 8 and try it? I think I got a bit over-enthusiastic with the 'fix'!

**Comment by ChristophBerg** [comment]
That fixes the "resources" cleanup check, but not the ipc check:

```
lib/check_ipc.c|998| 67000 ipc connections made
96%: Checks: 26, Failures: 0, Errors: 1
check_ipc.c:491:P:ipc_txrx_us_timeout:test_ipc_txrx_us_timeout:0: Passed
check_ipc.c:1464:P:ipc_max_dgram_size:test_ipc_max_dgram_size:0: Passed
check_ipc.c:491:P:ipc_server_fail_soc:test_ipc_server_fail_soc:0: Passed
check_ipc.c:491:P:ipc_txrx_us_block:test_ipc_txrx_us_block:0: Passed
check_ipc.c:491:P:ipc_txrx_us_tmo:test_ipc_txrx_us_tmo:0: Passed
check_ipc.c:657:P:ipc_fc_us:test_ipc_fc_us:0: Passed
check_ipc.c:491:P:ipc_exit_us:test_ipc_exit_us:0: Passed
check_ipc.c:491:P:ipc_dispatch_us:test_ipc_disp_us:0: Passed
check_ipc.c:491:P:ipc_stress_test_us:test_ipc_stress_test_us:0: Passed
check_ipc.c:491:P:ipc_bulk_events_us:test_ipc_bulk_events_us:0: Passed
check_ipc.c:491:P:ipc_event_on_created_us:test_ipc_event_on_created_us:0: Passed
check_ipc.c:1279:P:ipc_disconnect_after_created_us:test_ipc_disconnect_after_created_us:0: Passed
check_ipc.c:367:P:ipc_service_ref_count_us:test_ipc_service_ref_count_us:0: Passed
check_ipc.c:491:P:ipc_stress_connections_us:test_ipc_stress_connections_us:0: Passed
check_ipc.c:491:P:ipc_txrx_shm_timeout:test_ipc_txrx_shm_timeout:0: Passed
check_ipc.c:491:P:ipc_server_fail_shm:test_ipc_server_fail_shm:0: Passed
check_ipc.c:491:P:ipc_txrx_shm_block:test_ipc_txrx_shm_block:0: Passed
check_ipc.c:491:P:ipc_txrx_shm_tmo:test_ipc_txrx_shm_tmo:0: Passed
check_ipc.c:657:P:ipc_fc_shm:test_ipc_fc_shm:0: Passed
check_ipc.c:491:P:ipc_dispatch_shm:test_ipc_disp_shm:0: Passed
check_ipc.c:491:P:ipc_stress_test_shm:test_ipc_stress_test_shm:0: Passed
check_ipc.c:491:P:ipc_bulk_events_shm:test_ipc_bulk_events_shm:0: Passed
check_ipc.c:491:P:ipc_exit_shm:test_ipc_exit_shm:0: Passed
check_ipc.c:491:P:ipc_event_on_created_shm:test_ipc_event_on_created_shm:0: Passed
check_ipc.c:1420:P:ipc_service_ref_count_shm:test_ipc_service_ref_count_shm:0: Passed
check_ipc.c:995:E:ipc_stress_connections_shm:test_ipc_stress_connections_shm:0: (after this point) Test timeout expired
FAIL ipc.test (exit status: 1)

============================================================================
Testsuite summary for libqb 0.17.2
============================================================================
# TOTAL: 8
# PASS:  7
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

Full test log: https://paste.debian.net/313235/

**Comment by chrissie-c** [comment]
Yes, I'm looking at that one now. It's a *lot* more complicated!

**Comment by chrissie-c** [comment]
Ahh, OK it's just a timeout. I was hitting this on *BSD so I'm not sure if it's that the kevent code is much less efficient than epoll or that I'm running my *BSD tests in VMs rather than on hardware. I'm guessing the mips/mipsel hardware is not that fast.

If you increase the timeouts of the two stress_connections tests then I think that will fix it. Let me know if it does and I'll commit the change.


diff --git a/tests/check_ipc.c b/tests/check_ipc.c
index 26985df..cccb3b7 100644
--- a/tests/check_ipc.c
+++ b/tests/check_ipc.c
@@ -1539,7 +1539,7 @@ make_shm_suite(void)
 
        tc = tcase_create("ipc_stress_connections_shm");
        tcase_add_test(tc, test_ipc_stress_connections_shm);
-       tcase_set_timeout(tc, 200);
+       tcase_set_timeout(tc, 20000);
        suite_add_tcase(s, tc);
 
        return s;
@@ -1618,7 +1618,7 @@ make_soc_suite(void)
 
        tc = tcase_create("ipc_stress_connections_us");
        tcase_add_test(tc, test_ipc_stress_connections_us);
-       tcase_set_timeout(tc, 200);
+       tcase_set_timeout(tc, 20000);
        suite_add_tcase(s, tc);
 
        return s;

**Comment by chrissie-c** [comment]
A slightly lower timeout (1 hour) committed here https://github.com/ClusterLabs/libqb/commit/b635cc9703d0d9fa6ee665594cac9df929668cfe
