### ISSUE TITLE
Update config.sub+guess in the release tarballs

### ISSUE THREAD

**Issue by ChristophBerg** [ClusterLabs/libqb#166]
```
$ grep ^timestamp build-aux/config.*
build-aux/config.guess:timestamp='2009-11-20'
build-aux/config.sub:timestamp='2009-11-20'
```
These files are too old to support e.g. arm64:
```
Invalid configuration `aarch64-linux-gnu': machine `aarch64' not recognized
```

We can work around it for the Debian packages, but it would be nice if future releases had current copies of these files. Thanks!

(corosync has the same problem, btw.)

**Comment by chrissie-c** [comment]
Thanks for pointing that out. I think it's because we build the tarballs on RHEL6 workstations (well, I do anyway) which has an old-ish versions of automake. This might be a good excuse to upgrade :)

**Comment by chrissie-c** [comment]
1.0rc1 was build on RHEL7 so should be far more up-to-date.
