### ISSUE TITLE
libqb failing tests for IPC and RESOURCES on centos 7, arch armv7hl.

### ISSUE THREAD

**Issue by BJWTech** [ClusterLabs/libqb#182]
Trying to build an rpm for centos 7 armv7hl arch. Build server reports that it fails TESTS; ipc & resources;

`FAIL: ipc.test
FAIL: resources.test`

Here is the full output;

http://armv7.dev.centos.org/rpmbuild/c71511-pass-1/7366-libqb-0.17.1-2.el7/armv7hl/build.log

Any help? Thank you in advance!

**Comment by arrfab** [comment]
Probably related to https://github.com/ClusterLabs/libqb/issues/165, so we should find the correct patch for that version.

**Comment by chrissie-c** [comment]
On 16/02/16 04:56, BJWTech wrote:
> Trying to build an rpm for centos 7 armv7hl arch. Build server reports
> that it fails TESTS; ipc & resources;
> 
> |FAIL: ipc.test
> FAIL: resources.test|
> 
> Here is the full output;
> 
> http://armv7.dev.centos.org/rpmbuild/c71511-pass-1/7366-libqb-0.17.1-2.el7/armv7hl/build.log
> 
> Any help? Thank you in advance!
> 

Can you try the 1.0 release candidates please? They have 'fixes' for the
timeout issues that affect slow processors and ones without epoll.

Chrissie

**Comment by jnpkrn** [comment]
Feel free to use this SRPM:
https://people.redhat.com/jpokorny/pkgs/libqb/libqb-1.0-0.1.rc2.src.rpm
(used also for https://copr.fedorainfracloud.org/coprs/jpokorny/libqb/build/157747/)

**Comment by arrfab** [comment]
Well, we can try a build , but tis one will not make it into CentOS 7 userland for armhfp : using only upstream packages (with patches if needed), so in this case we'd need to build 0.17.1-2

**Comment by chrissie-c** [comment]
On 16/02/16 14:44, Fabian Arrotin wrote:
> Well, we can try a build , but tis one will not make it into CentOS 7
> userland for armhfp : using only upstream packages (with patches if
> needed), so in this case we'd need to build 0.17.1-2
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ClusterLabs/libqb/issues/182#issuecomment-184707072>.
> 

In that case you might have to add this commit to the CentOS build for
this release. 7.3 will be rebased to 1.0 so it will only be temporary.

https://github.com/ClusterLabs/libqb/commit/b635cc9703d0d9fa6ee665594cac9df929668cfe

**Comment by chrissie-c** [comment]
Closing this because I think it was solved ages ago. Feel free to reopen it if this isn't the case
