### ISSUE TITLE
[before 1.0] libqb version should be exposed in <qb/qbconfig.h>

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/libqb#186]
`libqb` users should have the info about the current library version readily available from one of its header files, `qb/qbconfig.h` seems best.

Suggested encoding:
```
QB_VER_MAJOR = 1
QB_VER_MINOR = 0
QB_VER_PATCH = 0
```

Thoughts?

**Comment by jnpkrn** [comment]
This would help such users to workaround missing properties/declarations. such as `enum qb_log_target_slot` (introduced in 4ccca4b), in a backward compatible way, without explicit need of out-of-band knowledge (such that coming from `configure` script).

**Comment by chrissie-c** [comment]
On 23/02/16 18:22, Jan Pokorný wrote:
> |libqb| users should have the info about the current library version
> readily available from one of its header files, |qb/qbconfig.h| seems best.
> 
> Suggested encoding:
> 
> |QB_VER_MAJOR = 1 QB_VER_MINOR = 0 QB_VER_PATCH = 0 |
> 
> Thoughts?

I had a think about this over the last few days, and while I like the
idea I worry that it's another thing that can get neglected during the
development/release process. And I think a version definition that's
neglected is worse than none at all.

Now if you came up with a system that automatically updates it, maybe
based on the library version in lib/Makefile.am ... ;-)

So I'm going to leave this for 1.0

Chrissie
