### ISSUE TITLE
[Problem] libqb does not seem to support a format of "%z".

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/libqb#215]
Hi All,

The output of the log of Pacemaker was changed by the next correction.
 * https://github.com/ClusterLabs/pacemaker/commit/fc87717a91fa8c5011c184c1ea3ce551b650037d#diff-985358aeb562c6ddf99399a97c1424ec

When I appoint PCMK_blackbox=yes, Pacemaker fails in start.
It seems to have a problem that libqb does not support %z format.

Best Regards,
Hideo Yamauchi.

**Comment by chrissie-c** [comment]
Proposed patch in PR#216

**Comment by HideoYamauchi** [comment]
Hi Christine,

Okay!
I test it on Monday.

Best Regards,
Hideo Yamaucuhi.

**Comment by sammcj** [comment]
Until resolved this likely blocks Redhat bug [1299968 - Rebase libqb to 1.0 for RHEL7.3](https://bugzilla.redhat.com/show_bug.cgi?id=1299968#c11)

**Comment by HideoYamauchi** [comment]
Hi Christine,

I confirmed that your correction solved a problem.
 * https://github.com/ClusterLabs/libqb/pull/216

Best Regards,
Hideo Yamauchi.

**Comment by chrissie-c** [comment]
Thanks for testing :)

**Comment by chrissie-c** [comment]
Added as commit 22ac41108ec3ad273905c67ac5ef5be01bb0f268

**Comment by HideoYamauchi** [comment]
Hi Christine,

Thanks!

**Comment by kgaillot** [comment]
Pacemaker has been updated to avoid using %z as of commit 380c1bb, which will be part of the 1.1.15 release. So, no released version of Pacemaker will have a problem with older versions of corosync without this patch.

**Comment by chrissie-c** [comment]
On 21/06/16 01:17, Ken Gaillot wrote:
> Pacemaker has been updated to avoid using %z as of commit 380c1bb, which
> will be part of the 1.1.15 release. So, no released version of Pacemaker
> will have a problem with older versions of corosync without this patch.

Thanks Ken

Chrissie

**Comment by HideoYamauchi** [comment]
Hi Ken,

All right!

Mant thanks!
Hideo Yamauchi.

**Comment by sammcj** [comment]
Just taking a moment here to say thank you to the ClusterLabs and RHEL communities, both have been so fantastic to work with and so many people really care about the quality and progression of even little issues like this. Thanks everyone 👍
