### ISSUE TITLE
failure on x32 architecture

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/libqb#219]
Reported by Debian Package Auto-Building (via https://github.com/ClusterLabs/libqb/pull/192#issuecomment-227713467):

https://buildd.debian.org/status/fetch.php?pkg=libqb&arch=x32&ver=1.0-1&stamp=1466593341

```
check_ipc.c:1464:F:ipc_max_dgram_size:test_ipc_max_dgram_size:0: Assertion 'init == try' failed: init == 200192, try == 199680
```

**Comment by chrissie-c** [comment]
Oddly this works on the (slightly older) Debian-x32 I downloaded with glibc 2.19 rather than 2.22

**Comment by chrissie-c** [comment]
it also works (for me) on glibc 2.22-13 (that buildd is for 2.22.12) so closing for now.
