### ISSUE TITLE
Please sign the uncompressed release tarball or each compressed one

### ISSUE THREAD

**Issue by wferi** [ClusterLabs/libqb#220]
It's great that you now distribute proper signed releases, it really makes packaging your software much easier. However, the Debian helper scripts aren't prepared to validate your two-step scheme (checking the detached signature of the sha256sum file, then checking the hash of the compressed tarball against that). While we could implement this on our part, maybe you'd agree to switch to a more usual scheme, that is, to signing the uncompressed tarball or signing each compressed tarball separately. Both avoid (but does not forbid) the sha256sum files. The latter method requires multiple signatures, but is the simplest to handle on the receiver side.
Thanks for your consideration.

**Comment by jnpkrn** [comment]
Perhaps the most reasonable way out is to say bye to `tar.gz` and distribute solely `tar.xz` + it's signature. At worst, downstream would be forced to recompress (still verifiable) tarball, but note that `tar` supports `xz` pass-through as of 7+ years ago.

**Comment by chrissie-c** [comment]
I don't see any real problem with signing both compressed tarballs if that will help packagers.

**Comment by wferi** [comment]
Yes please, that would be great! And then we wouldn't need the SHA256 files anymore.

**Comment by wferi** [comment]
Hi, did you intend to sign the compressed tarballs of 1.0.1? :)

**Comment by jnpkrn** [comment]
@wferi, regarding #236, are `.asc` signatures OK?

**Comment by wferi** [comment]
Yes, @jnpkrn, ASCII armored signatures would be great. Just like raw ones. It does not matter, really.

**Comment by wferi** [comment]
Hi, why not check the machinery on the fresh 1.0.2 release? :)

**Comment by chrissie-c** [comment]
Should have closed this with 1.0.2!
