### ISSUE TITLE
document availability on openSUSE

### ISSUE THREAD

**Issue by aspiers** [ClusterLabs/libqb#225]
[`libqb` is available on openSUSE](https://software.opensuse.org/package/libqb) but this is omitted from [the wiki](https://github.com/ClusterLabs/libqb/wiki).  I would have fixed it myself but apparently it's not a world-writable wiki.

**Comment by chrissie-c** [comment]
On 05/10/16 11:39, Adam Spiers wrote:
> |libqb| is available on openSUSE
> <https://software.opensuse.org/package/libqb> but this is omitted from
> the wiki <https://github.com/ClusterLabs/libqb/wiki>. I would have fixed
> it myself but apparently it's not a world-writable wiki.
>

Thanks for pointing this out. I've fixed the wiki now

Chrissie

**Comment by jnpkrn** [comment]
Is everyone satisfied so that this can possibly be closed?
Or is more granularity distro-wise desired?

Just asking as this got a bit stale, possibly pending closure.

**Comment by chrissie-c** [comment]
I'll close it.Feel free to re-open if more detail is  needed.
