### ISSUE TITLE
IPC sending is not thread-safe

### ISSUE THREAD

**Issue by chrissie-c** [ClusterLabs/libqb#243]
If two threads send at the same time using SHM IPC then the ringbuffer can get corrupted and the server process will spin until the client is disconnected.

**Comment by jnpkrn** [comment]
There's some issue management missing :)

We can call this one resolved (as in "it's up to the library user, really")
as of 60122a4 (+ follow up cleanup).

**Comment by chrissie-c** [comment]
yep. I'll close it, thanks.,
