### ISSUE TITLE
[RFE] IPC functions shouldn't log above debug level

### ISSUE THREAD

**Issue by kgaillot** [ClusterLabs/libqb#273]
Functions such as qb_ipcs_event_send() log warnings on some, but not all, errors, and return an error code to the caller.

My feeling is that the caller should decide whether and how to log the error, as it has greater context, and libqb can provide any useful information via the error code. For example, the caller may wish to ignore certain error codes, and the libqb warnings could unnecessarily alarm users in that case.

If dropping the logs is too much, logging at debug or trace level would be acceptable.

If there are common libqb applications that depend on libqb to do the logging, we can keep it as is, but I suspect most callers will check the return value and log an error of their own when appropriate.

**Comment by jnpkrn** [comment]
Agree that incosistency plays against us for sure.  Wonder if it should be configurable by some
means, e.g. built on top of the log tagging?

**Comment by jnpkrn** [comment]
Indeed, the libqb client can modify the libqb's own logging as current means
already provide enough flexibility, using the tagging as mentioned,
together with the fact libqb's own log callsites are pre-tagged on
`QB_LOG_TAG_LIBQB_MSG_BIT` in the bitmask:

```
static void
m_filter(struct qb_log_callsite *cs)
{
        int32_t t;
        if (qb_bit_is_set(cs->tags, QB_LOG_TAG_LIBQB_MSG_BIT)) {
                for (t = 0; t < QB_LOG_TARGET_MAX; t++) {
                        /* or conditionalize futher here */
                        qb_bit_clear(cs->targets, t);
                }
        }
}

[...]

        qb_log_init("foobar", LOG_..., LOG_...);
        /* perform all the logging setup here */
        qb_log_filter_fn_set(m_filter);

[...]
```

Or the setup can go a little deeper, which is what corosync currently does,
though enumerating the source files feels pretty clumsy:
https://github.com/corosync/corosync/blob/v2.4.3/exec/logsys.c#L319-L335

Perhaps having #133 resolved would help a bit here, but that would not be
backward compatible.

Do we want to keep this open to tackle any inconsistencies found?

**Comment by kgaillot** [comment]
#133 or one of the existing approaches should cover it
