### ISSUE TITLE
Allow control of maximum log line length

### ISSUE THREAD

**Issue by kgaillot** [ClusterLabs/libqb#275]
Currently, QB_LOG_MAX_LEN is hardcoded to 512, and longer lines are truncated when written to a log file. It would be desirable to have this configurable e.g. by a QB_LOG_CONF_* option. The maximum line length could be configured per log target, and the actual buffer allocated to the maximum of those.

**Comment by jnpkrn** [comment]
Point in case (along with #276):
http://oss.clusterlabs.org/pipermail/users/2016-November/004428.html

That length is used extensively in libqb and even constrained in blackbox binary
format.  Plus there are historical limits of what syslog is supposed to handle:
https://stackoverflow.com/a/41822232

Any general solution won't be exactly easy, perhaps the easiest amongst them
being artificial message chunking.  And clients are free to go that route right now,
they have the boundary length available as a defined macro in `qblog.h`.

**Comment by jnpkrn** [comment]
And operationally, how many administrators will be pleased by excessively long lines?

**Comment by jnpkrn** [comment]
Systemd was also facing the "too strict" limit (2KB in that case), for
stdin/stdout absorption (which feels naturally a more relaxed "logging"
interface):
- https://lists.freedesktop.org/archives/systemd-devel/2017-October/039589.html (3rd bullet)
- https://github.com/systemd/systemd/commit/ec20fe5ffb8a00469bab209fff6c069bb93c6db2
- https://bugs.freedesktop.org/show_bug.cgi?id=86465

(However, it looks like the only other boundary is 768 MiB per message.)

**Comment by chrissie-c** [comment]
pr#292

**Comment by chrissie-c** [comment]
Now an option. pr #292
