### ISSUE TITLE
Print ellipsis when truncating a log line

### ISSUE THREAD

**Issue by kgaillot** [ClusterLabs/libqb#276]
Users have expressed some confusion when log lines silently get truncated. It would be worthwhile to end truncated log lines with "..." to provide an indication that it was truncated. If you want to avoid changing existing behavior, this might be enabled by a QB_LOG_CONF_* option.

**Comment by jnpkrn** [comment]
Point in case (along with #275):
http://oss.clusterlabs.org/pipermail/users/2016-November/004428.html
(last message in the thread)
