### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by bastelfreak** [ClusterLabs/libqb#278]
Hi everybody,
thanks for the good work on this software! I'm packaging this for Archlinux. Is it possible to create new release? The last one was quite some time ago.

Cheers, Tim

**Comment by jnpkrn** [comment]
I think the tentative plan is to release a new version once #266 is merged
(with some minor change to be made) and the maintainers cooperate on
pushing the button, which may happen on Tue next week.

**Comment by kgaillot** [comment]
Hi Tim,

I'm curious ... Is your goal to get the whole cluster suite packaged? How much demand have you seen for it in the Arch world? Feel free to let us know about any incompatibilities in the build process you have to work around, whether in an issue like this or on the developers@clusterlabs.org mailing list.

**Comment by bastelfreak** [comment]
Hi,
I try to package the whole cluster suite, yes. Besides myself, I know a few other people that are interested in it, but I don't know about the demand in the whole community. At the moment everything is working, We just like regular releases with a few changes, instead of big ones. I will let you know if I find any issues during the builds.

**Comment by chrissie-c** [comment]
Yes there will definitely be a release before the Christmas break, I'm just waiting for\a couple of PRs and then I'll do it.

**Comment by chrissie-c** [comment]
I'm REALLY sorry, but the changes that poki made for the logging have broken the maintainer-clean target and therefore  also the release system. I don't have time to fix it at the moment but as soon as we can get this fixed I'll do a release in the new year.

**Comment by bastelfreak** [comment]
Thanks for the update. That is totally okay for me.

**Comment by chrissie-c** [comment]
poki to the rescue - 1.0.3 is now out. I still need to fix the doc (hence I'll leave this open)

**Comment by chrissie-c** [comment]
V2.0.0 was released on 4th May so closing this.
