### ISSUE TITLE
[RFE] Add support for structured logging to reflect the shift towards machine log processing

### ISSUE THREAD

**Issue by jnpkrn** [ClusterLabs/libqb#286]
This is an intended prerequisite to add support for new log back-ends like:
* native journald handover
  - https://freedesktop.org/software/systemd/man/sd_journal_send.html
  - https://freedesktop.org/software/systemd/man/systemd.journal-fields.html
* The OpenTracing Semantic Specification compliant back-end
  - https://github.com/opentracing/specification/blob/master/specification.md#the-opentracing-api
  - https://github.com/opentracing/specification/blob/master/semantic_conventions.md#standard-span-tags-and-log-fields

**Comment by jnpkrn** [comment]
Possibly interesting in this context:
https://is.muni.cz/th/172673/fi_d/thesis-twoside-final-bw.pdf

**Comment by jnpkrn** [comment]
For how Linux deals with this task:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/printk/printk.c?h=v4.19#n309

**Comment by jnpkrn** [comment]
Ah, even RFC exists (proposed standard, exists since 2009):
https://tools.ietf.org/html/rfc5424

**Comment by jnpkrn** [comment]
Regarding prior work, it's good to also mention `logfmt`, detailed,
e.g., in https://brandur.org/logfmt

**Comment by jnpkrn** [comment]
See a particular motivational example:
[structured logging flag to mark secrecy-sensitive log items](https://github.com/ClusterLabs/libqb/pull/433#issuecomment-796318679)

**Comment by chrissie-c** [comment]
Closing this as there has been no call for it.
