### ISSUE TITLE
[RFC] drop CORP and travis integration

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/libqb#301]
The new CI infrastructure is now testing libqb. COPR and travis integration can be decommissioned.

**Comment by chrissie-c** [comment]
Yep, I'm definitely in favour of this. the new CI is something we have far more control over and integrates into knet & corosync too.

**Comment by jnpkrn** [comment]
Well, I definitely have more control over standardized service running
under Fedora's umbrella.  Live and let live, it doesn't interfere with
anything.

**Comment by chrissie-c** [comment]
poki, you are quite free to express opinions here and engage in civilised discussions where we will come to a conclusion together. But do NOT close issues unilaterally like that.

**Comment by jnpkrn** [comment]
No interferences were brought up, hence I don't see what's to be discussed
here.  New hooks to be added?  Fine, it doesn't affect existing ones,
or do I miss something?  More CI handlers is an HA approach, after all.
I am all for civilised discussion on `either-or` things.

**Comment by chrissie-c** [comment]
As it is I don't see the need to remove COPR/travis at the moment as it's proving useful. It might be worth revisiting this when the full cluster stack is in Jenkins.

**Comment by chrissie-c** [comment]
Travis was removed in b21d9a66dba9a14ad25c51e9a019e599ebac1bfd
