### ISSUE TITLE
libqb 1.0.3 PACKAGE_VERSION is UNKNOW

### ISSUE THREAD

**Issue by sasadangelo** [ClusterLabs/libqb#312]
Hi,

I am trying to use libqb 1.0.3 with pacemaker and corosync to create a cluster and I think I found a bug. I compiled libqb as per doc but in /usr/lib/pkgconfig/libqb.pc in the Version field I found UNKNOWN.
This arise an issue in Pacemaker when I launch ./configure because it check with pkg-config if the library it is greater than 0.13. The check fails reporting that 0.13 was expected but UNKNOWN was found. I simply fixed the issue replacing the correct value in /usr/lib/pkgconfig/libqb.pc, but I think code must be fixed.

**Comment by edwintorok** [comment]
Have you built libqb from the git tag or from the released tarball. I think the tarball differs from the git tag in that it has a .tarball-version inside it. 
Perhaps the right way of fixing this would be to enable `export-subst` in `.gitattributes` on the .pc file and use git archive substitution formats to get the version number substituted into the file.
That way when you generate a tarball from a git tag using `git archive` you would get the correct version inside it.

**Comment by jnpkrn** [comment]
Sorry, but using "native on-the-fly archives" is not a supported
use case at this time.  Sadly, GitHub is obnoxious enough that we
cannot turn that "feature" (making for unintended misfeature here;
accidentally, it was discussed recently at the `developers` mailing
list that patchset review process leaves rather too much to be
desired, too).  In turn, we cannot be held accountable for something
we don't want to endorse in the first place, though we can probably
better document the matter.

Your options:

1. use proper (and stable and signed!) archives (you can recognize
   these for having a static file size that's displayed along the
   respective "Assets" per-release items)

2. `git clone [...]; git checkout $TAG; ./autogen.sh && ./configure [...]`
   possibly followed with, e.g., `make dist-xz`

Closing, though feel free to reopen if the above options don't suite
you for some reason.

**Comment by jnpkrn** [comment]
![hopethishelps](https://user-images.githubusercontent.com/1391681/42352448-e1ca8e86-80ba-11e8-9899-40c28125154b.png)

**Comment by chrissie-c** [comment]
Annoyingly github insists on putting the useless "Source Code" archives in the release list. I really wish they wouldn't.

**Comment by sasadangelo** [comment]
Ok it worked. Thanks.
