### ISSUE TITLE
virtual_ip	(ocf::heartbeat:IPaddr2):	Stopped

### ISSUE THREAD

**Issue by philbertb** [ClusterLabs/libqb#346]
Hello, i keep seeing this status.

I already did below. But still getting same status.

#crm resource restart virtual_ip
INFO: ordering virtual_ip to stop
INFO: ordering virtual_ip to start

#crm configure show
node 1: ubuntu-web01 \
        attributes standby=off maintenance=off
node 2: ubuntu-web02 \
        attributes standby=off
node 3: ubuntu-web03 \
        attributes standby=off
primitive ClusterIP IPaddr2 \
        params ip=192.168.56.155 cidr_netmask=24 \
        op monitor interval=30 \
        meta target-role=Started is-managed=true
primitive virtual_ip IPaddr2 \
        params ip=192.168.56.154 cidr_netmask=32 \
        op monitor interval=10s \
        meta migration-threshold=10 target-role=Started is-managed=true
primitive webserver nginx \
        params configfile="/etc/nginx/nginx.conf" \
        op start timeout=40s interval=0 \
        op stop timeout=60s interval=0 \
        op monitor interval=10s timeout=60s \
        meta migration-threshold=10 target-role=Started is-managed=true
group nginx-resourcegroup-byphilbong virtual_ip webserver \
        meta target-role=Started is-managed=false
location cli-prefer-nginx-resourcegroup-byphilbong nginx-resourcegroup-byphilbong role=Started inf: ubuntu-web02
property cib-bootstrap-options: \
        have-watchdog=false \
        dc-version=1.1.14-70404b0 \
        cluster-infrastructure=corosync \
        cluster-name=debian \
        stonith-enabled=false \
        no-quorum-policy=ignore \
        last-lrm-refresh=1554385737 \
        stonith-enabled-false \
        stonith-enabled-false \
        stonith_enabled=true \
        stonith-enabled-false \
        stonith-enabled-false \
        --delete

How do i get rid of the property " cib-bootstrap-options: \ "  as they were typed in wrongly.
-------------------------
stonith-enabled-false \
        stonith-enabled-false \
        stonith_enabled=true \
        stonith-enabled-false \
        stonith-enabled-false \
        --delete
--------------------------

Thank you,

Philbert

**Comment by chrissie-c** [comment]
That's  pacemaker issue. you should really report it over here: https://github.com/ClusterLabs/pacemaker/

**Comment by jnpkrn** [comment]
First, it wasn't pacemaker issue per se, second, pacemaker deliberately
doesn't accept users' issues debates via GitHub, end result being just
an unncessary out-of-context next hop attempt:
https://github.com/ClusterLabs/pacemaker/pull/1740#issuecomment-480245514
