### ISSUE TITLE
Blackbox files need a format version somewhere

### ISSUE THREAD

**Issue by beekhof** [ClusterLabs/libqb#35]
If you ever change the on-disk format (perhaps by adding extra fields like log level), you want to gracefully fail when attempting to read files created with older/newer versions.

**Comment by jnpkrn** [comment]
Note the "portability" aspect is rather wider:
https://github.com/ClusterLabs/libqb/pull/262/commits/f5d85bf186ba0a61fbaaeeab73a3765a47bcac9a
