### ISSUE TITLE
can not build on linux-mips

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/libqb#351]
usr/bin/ld: warning: /root/ra-source/libqb-1.0.5/lib/qblog_script.ld contains output sections; did you forget -T?
/usr/bin/ld: section __verbose loaded at [0000000000000210,0000000000001a47] overlaps section .MIPS.options loaded at [0000000000000120,0000000000000647]
/usr/bin/ld: section .note.gnu.build-id loaded at [0000000000000648,000000000000066b] overlaps section __verbose loaded at [0000000000000210,0000000000001a47]
/usr/bin/ld: .libs/libqb.so.0.19.2: section __verbose vma 0x210 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .note.gnu.build-id vma 0x648 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .dynamic vma 0x670 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .hash vma 0x870 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .dynsym vma 0x1298 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .dynstr vma 0x36b0 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .gnu.version vma 0x4fa4 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .gnu.version_r vma 0x52a8 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .rel.dyn vma 0x53a8 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .init vma 0x80f8 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .text vma 0x8180 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .MIPS.stubs vma 0x1fba0 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .fini vma 0x20300 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .rodata vma 0x20350 overlaps previous sections
/usr/bin/ld: .libs/libqb.so.0.19.2: section .eh_frame vma 0x23c70 overlaps previous sections

**Comment by chrissie-c** [comment]
Can you try building from git 'master' please and see if that helps? It eliminates the linker 'magic' that the v1 series depends on.

**Comment by GitSoftwareNow** [comment]
> It eliminates the linker 'magic' that the v1 series depends on
 It eliminates the linker 'magic' that the v1 series depends on

what's this?

**Comment by chrissie-c** [comment]
Closing this as it's probably fixed in the 2.0 series and I can't test it. Feel free to re-open if it's still a problem.
