### ISSUE TITLE
I can't understand the discribe of such code

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/libqb#360]
libqb project:
coding such as discribe
#ifdef QB_HAVE_ATTRIBUTE_SECTION
#define qb_logt(priority, tags, fmt, args...) do {			\
	static struct qb_log_callsite descriptor			\
	__attribute__((section(QB_ATTR_SECTION_STR), aligned(8))) =	\
	{ __func__, __FILE__, fmt, priority, __LINE__, 0, tags };	\
	qb_log_real_(&descriptor, ##args);				\
    } while(0)
#else
#define qb_logt(priority, tags, fmt, args...) do {	\
	struct qb_log_callsite* descriptor_pt =		\
	qb_log_callsite_get(__func__, __FILE__, fmt,	\
			    priority, __LINE__, tags);	\
	qb_log_real_(descriptor_pt, ##args);		\
    } while(0)
#endif /* QB_HAVE_ATTRIBUTE_SECTION */

what can I do called the function "qb_log_callsite_get" and "qb_log_real"

**Comment by GitSoftwareNow** [comment]
@zhiyong0804

**Comment by chrissie-c** [comment]
It's  internal code that is removed in the master branch anyway, so don't worry about it.

It was there to support the use of linker sections for collecting callsites, but it ended up more trouble than it was worth. When I get chance I'll start a 2.0 series that has this code removed. I'm just super-busy on other things at the moment.
