### ISSUE TITLE
an issue in the log_syslog.c 

### ISSUE THREAD

**Issue by GitSoftwareNow** [ClusterLabs/libqb#362]
how do you call the syslog function to print debug infomation on CentOS series operating system
when I tried to call syslog() the first argument to use l LOG_SYSLOG but it can not print debug infomation on /var/log/message ,what's the reason? how can I resolve it?

**Comment by chrissie-c** [comment]
Check that DEBUG messages are enabled in the syslog configuration file /etc/rsyslog.conf or, if you're using the journal that debug messages are enabled there. They are no on by default.

Also, generic syslog questions are more suited to stackoverflow.com than here.

**Comment by GitSoftwareNow** [comment]
@chrissie-c  libqb use default configuration file /etc/rsyslog.conf ,it can print DEBUG messages , the reason ?

**Comment by GitSoftwareNow** [comment]
@chrissie-c libqb uses default configuration file /etc/rsyslog.conf ,it can print DEBUG messages , the reason ?
