### ISSUE TITLE
[HEAD/1.9.0] Release tarballs contain (and will contain) empty configure.ac

### ISSUE THREAD

**Issue by hartwork** [ClusterLabs/libqb#375]
I'm aware that `configure` — not `configure.ac` — is important to build but an empty `configure.ac` — unlike in Git — in the release archive seems weird and not ideal to me:

```console
# wget -O- https://github.com/ClusterLabs/libqb/releases/download/1.9.0/libqb-1.9.0.tar.xz 2>/dev/null | tar -tJv | fgrep configure.ac
-rw-rw-r-- 500/500           0 2019-12-12 14:27 libqb-1.9.0/configure.ac
                            ^^^
```

Git `master` still has this problem so the next release off `master` will be affected:

```console
# git clone https://github.com/ClusterLabs/libqb.git
# cd libqb
# ./autogen.sh && ./configure && make dist
# tar tvf libqb-1.9.0.tar.gz | fgrep configure.ac
-rw-r--r-- 1000/1000         0 2020-01-02 20:56 libqb-1.9.0/configure.ac
                            ^^^
```

From what I can see, this code is at fault:
https://github.com/ClusterLabs/libqb/blob/51a03aa9c6f4c3b208f449e73a6b67228147260d/Makefile.am#L127-L134

Line 131 only generates `$(builddir)/configure.ac-t` *in some cases*.
Line 132 steps in to create the file empty *otherwise* — that's our case — using `touch`.
On a side note, line 133 seems to also target the wrong file.

What do you think?

**Comment by chrissie-c** [comment]
It's definitely wrong and needs fixing, thanks for letting us know.  I'll look at it in more detail when I get through the 'back to work' backlog !

**Comment by fabbione** [comment]
should be fixed by https://github.com/ClusterLabs/libqb/pull/376

**Comment by hartwork** [comment]
Looks pretty good but the `chmod` line still applies to the wrong file, if I'm not mistaken:
https://github.com/ClusterLabs/libqb/blob/0f67f848131aa6aef8fc2dd05f246f5d68fabb19/Makefile.am#L134

**Comment by fabbione** [comment]
Yes you are right. My bad. I´ll open another PR.

**Comment by fabbione** [comment]
https://github.com/ClusterLabs/libqb/pull/377

there and thanks for spotting it.

**Comment by jnpkrn** [comment]
Thanks for the report, it seems that the state after all these
changes were indeed meant originally, but I guess I missed that
for `make distcheck` generally working, IIRC, so it was really
just a matter of being attentive to detail -- thanks @hartwork
for that.

**Comment by hartwork** [comment]
That was quick — thank you! :+1:
