### ISSUE TITLE
Chain of trust for new release signing key

### ISSUE THREAD

**Issue by diabonas** [ClusterLabs/libqb#398]
Starting from version [1.9.0](https://github.com/ClusterLabs/libqb/releases/tag/1.9.0), releases are signed by the new release signing key [`C5E29348A2B634E9F71B2014791890532CB5CDDE`](https://sks-keyservers.net/pks/lookup?op=vindex&fingerprint=on&exact=on&search=0xC5E29348A2B634E9F71B2014791890532CB5CDDE), while previous releases were signed by the (now expired) key [`EA78541A2D92451106C8A1F7B67157F3A70D4537`](https://sks-keyservers.net/pks/lookup?op=vindex&fingerprint=on&exact=on&search=0xEA78541A2D92451106C8A1F7B67157F3A70D4537). Since the new key is not signed by the old one, it is currently not possible to verify whether this new key is genuine and can be trusted to upgrade from libqb <= 1.0.5 to version 1.0.6 or 2.0.0.

Could you please sign the new key `C5E29348A2B634E9F71B2014791890532CB5CDDE` with the old `EA78541A2D92451106C8A1F7B67157F3A70D4537` to establish a chain of trust?

**Comment by anthraxx** [comment]
An alternative approach would be to sign a text using the old key that states the full fingerprint of the new key and put it somewhere :smile_cat:

**Comment by chrissie-c** [comment]
Good  point. The libqb signing key should now be signed with my old key. let me know if it's not showing up.

Thanks for pointing this out.

**Comment by diabonas** [comment]
Thank you for your very quick reaction, much appreciated! For reference for future readers, the chain of trust is as follows:

- The new release signing key [`C5E29348A2B634E9F71B2014791890532CB5CDDE`](http://pgp.net.nz:11371/pks/lookup?op=vindex&search=0x791890532CB5CDDE) has been signed by [`E758C0F8B8BA45C337292662FAC74624967D696A`](http://pgp.net.nz:11371/pks/lookup?op=vindex&search=0xFAC74624967D696A).
- [`E758C0F8B8BA45C337292662FAC74624967D696A`](http://pgp.net.nz:11371/pks/lookup?op=vindex&search=0xFAC74624967D696A) (a previously expired key whose expiry date has been extended today) is in turn signed by [`EA78541A2D92451106C8A1F7B67157F3A70D4537`](http://pgp.net.nz:11371/pks/lookup?op=vindex&search=0xB67157F3A70D4537), which is the old key used to sign libqb <= 1.0.5 releases.

Hence there is an unbroken signature chain from the old to the new release signing key, establishing the authenticity of the latter.
