### ISSUE TITLE
Unable to find the new release signing key

### ISSUE THREAD

**Issue by wferi** [ClusterLabs/libqb#413]
New releases are signed by PGP key 0x791890532CB5CDDE, but I failed to find it: http://pgp.mit.edu, https://keys.openpgp.org and the SKS network didn't return anything.
Could you please publish it at some prominent place (preferably signed with the old key)?

**Comment by chrissie-c** [comment]
Hmm sorry, I thought I had sent the key to the keyservers a while ago. I've done it again just now and checked that it came down from pool.sks-keyservers.net. the two you mention are download-only servers so I can't send to them explicitly unless you know a way of doing that.

**Comment by wferi** [comment]
Thanks! I think pgp.mit.edu is a member of the SKS network, so no need to upload there separately (and it doesn't work for me at all anyway). As for the other, https://keys.openpgp.org/upload exists, but I don't know if this key (with such an email address) belongs there.
