### ISSUE TITLE
doxygen2man generates incomplete \f escape sequence

### ISSUE THREAD

**Issue by wferi** [ClusterLabs/libqb#419]
There are two occasions in the libqb documentation:
```
qb_log_real_ \- Internal function: use \fIqb_log()\fR or \fIqb_logt()\f
qb_util_stopwatch_split_last \- Get the last split index to be used by \fIqb_util_stopwatch_time_split_get()\f
```
Since plain `\f` alone is invalid, groff emits `a newline character is not allowed in an escape name` for the 4th lines of the respective manuals.

**Comment by chrissie-c** [comment]
Thanks .PR#420 should fix this.

**Comment by wferi** [comment]
Seems to help indeed, thanks!

**Comment by chrissie-c** [comment]
Thanks for checking. #420 is now merged
