### ISSUE TITLE
Internal strlcpy underflows on zero buffer size

### ISSUE THREAD

**Issue by wferi** [ClusterLabs/libqb#429]
The `QB_MIN(maxlen-1, srclen)` expression underflows for `maxlen=0` because `maxlen` is unsigned, thus `strlcpy(d,s,0)` becomes `strcpy(d,s)` contrary to the function documentation. I don't think it affects the current code base, but probably worth fixing nevertheless to avoid future accidents.

**Comment by chrissie-c** [comment]
Fixed in 5097155bdf39bd18a778b985354b0b38fd499f55
