### ISSUE TITLE
why I executed `make install` will generate a additional so file(libqb.so.0.19.3)?

### ISSUE THREAD

**Issue by harkue** [ClusterLabs/libqb#442]
why I executed `make install` will generate an additional so file(libqb.so.0.19.3)? 

Following the `INSTALL` document, I have executed commands as: 
```
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
```

check the lib I have installed
```
$[/root/libqb]# ls /usr/lib64/libqb*
/usr/lib64/libqb.a  /usr/lib64/libqb.la  /usr/lib64/libqb.so  /usr/lib64/libqb.so.0  /usr/lib64/libqb.so.0.19.3

```

**Comment by fabbione** [comment]
This is perfectly normal and correct.

libqb.so and libqb.so.0 are symlinks to libqb.so.0.19.3

**Comment by harkue** [comment]
> This is perfectly normal and correct.
> 
> libqb.so and libqb.so.0 are symlinks to libqb.so.0.19.3

Thanks for your reply.
