### ISSUE TITLE
Provide an example `qb` uri

### ISSUE THREAD

**Issue by summercms** [ClusterLabs/libqb#445]
Hello,

I'm just going through the IANA list of uri schemes and I notice that you haven't provided an example uri on the page: 

https://www.iana.org/assignments/uri-schemes/prov/qb

I've looked through this repo and can't find any mention of an example uri.

For example I'm wanting to know if the uri scheme is using a `:` or `://` structure?

e.g. 

```
qb:<value>
```

or

```
qb://<value>
```

etc.

If someone could reply with a syntax of the `qb` uri that would be great.

An example syntax for the [bitcoin](https://www.iana.org/assignments/uri-schemes/prov/bitcoin) protocol scheme is this:

```
Scheme syntax:

bitcoin:<address>[?[amount=<size>][&][label=<label>][&][message=<message>]]
```

Thanks in advance.

**Comment by kgaillot** [comment]
Hi,

The scheme reservation was part of a proposal that never moved forward. There is no qb URI scheme implemented or planned at this time.
