### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by Mingli-Yu** [ClusterLabs/libqb#446]
\# which crmadmin
/usr/sbin/crmadmin

 \# crmadmin
crmadmin: utils.c:50: common: Assertion `"libqb's callsite section is observable, otherwise libqb's build is at fault, preventing reliable logging" && work_s1 != NULL && work_s2 != NULL' failed.
Aborted
 \# rpm -qa|grep libqb
libqb-2.0.3-r0.corei7_64

**Comment by kgaillot** [comment]
Hi,

Thanks for the report!

What OS and which version of pacemaker are you using? That will help isolate what code produced the message.

**Comment by Mingli-Yu** [comment]
The  current pacemaker is 2.0.5 and the issue is gone after I upgrade pacemaker to 2.1.1.
