### ISSUE TITLE
[RFE] Async connect

### ISSUE THREAD

**Issue by wenningerk** [ClusterLabs/libqb#449]
For single-threaded clients there is currently no way to use the client-API if a certain reactivity
is needed while connecting to an IPC-server.
qb_ipcc_connect may take a kind of undefined time.
Alternative/supplementary solution to an async-API for connections might be adding some way
to define a timeout for the current sync-API.
Application currently in mind would be a liveness-check for multiple libqb-IPC-server-daemons.

**Comment by chrissie-c** [comment]
Added in https://github.com/ClusterLabs/libqb/pull/450
