### ISSUE TITLE
Program terminated with signal SIGBUS

### ISSUE THREAD

**Issue by ddzrc** [ClusterLabs/libqb#465]
Program terminated with signal SIGBUS, Bus error.
#0  0x00007f1228043280 in qb_rb_open_2 (name=name@entry=0x7f1217ffbb38 "svtp_check-request-4674-26738-31", size=71, flags=flags@entry=9, shared_user_data_size=shared_user_data_size@entry=4,
    notifiers=notifiers@entry=0x0) at ringbuffer.c:199
199     ringbuffer.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1217fff700 (LWP 4677))]
(gdb) bt
#0  0x00007f1228043280 in qb_rb_open_2 (name=name@entry=0x7f1217ffbb38 "svtp_check-request-4674-26738-31", size=71, flags=flags@entry=9, shared_user_data_size=shared_user_data_size@entry=4,
    notifiers=notifiers@entry=0x0) at ringbuffer.c:199
#1  0x00007f122804357e in qb_rb_open (name=name@entry=0x7f1217ffbb38 "svtp_check-request-4674-26738-31", size=<optimized out>, flags=flags@entry=9,
    shared_user_data_size=shared_user_data_size@entry=4) at ringbuffer.c:121
#2  0x00007f1228048b41 in qb_ipcs_shm_rb_open (c=c@entry=0x7f1210001a90, ow=ow@entry=0x7f1210001bd8, rb_name=rb_name@entry=0x7f1217ffbb38 "svtp_check-request-4674-26738-31") at ipc_shm.c:266
#3  0x00007f1228048d45 in qb_ipcs_shm_connect (s=0x24c9d30, c=0x7f1210001a90, r=0x7f1217ffbb00) at ipc_shm.c:313
#4  0x00007f122804965c in handle_new_connection (s=s@entry=0x24c9d30, auth_result=auth_result@entry=0, sock=sock@entry=31, msg=msg@entry=0x7f1217ffec50, len=len@entry=32,
    ugp=ugp@entry=0x7f1217ffec30) at ipc_setup.c:564
#5  0x00007f1228049b19 in qb_ipcs_us_connection_acceptor_base (fd=fd@entry=17, revent=revent@entry=1, data=data@entry=0x24c9d30) at ipc_setup.c:810
#6  0x00007f1228049c02 in qb_ipcs_us_connection_acceptor (fd=17, revent=1, data=0x24c9d30) at ipc_setup.c:844
#7  0x00007f1228044f75 in _poll_dispatch_and_take_back_ (item=0x7f1210001500, p=<optimized out>) at loop_poll.c:98
#8  0x00007f1228044a81 in qb_loop_run_level (level=level@entry=0x24c9a00) at loop.c:44

**Comment by wenningerk** [comment]
Don't know if it is something well known so that people who are into it would right away be able to tell ...
Anyway a little more info would be useful. Like at least versions of libqb and pmxcfs and what you were trying, if it is reproducible ...
Line numbers don't make much sense if you don't know where to exactly look ... ;-)

**Comment by ddzrc** [comment]
> Don't know if it is something well known so that people who are into it would right away be able to tell ... Anyway a little more info would be useful. Like at least versions of libqb and pmxcfs and what you were trying, if it is reproducible ... Line numbers don't make much sense if you don't know where to exactly look ... ;-)

version：0.16
because we have add log info, Please ignore the line number I pasted
the actual is：
      line number: lib/ringbuffer.c:195
       code: rb->shared_hdr->word_size = real_size / sizeof(uint32_t);
thanks！

**Comment by chrissie-c** [comment]
On 25/05/2022 08:17, wenningerk wrote:
> Don't know if it is something well known so that people who are into it 
> would right away be able to tell ...
> Anyway a little more info would be useful. Like at least versions of 
> libqb and pmxcfs and what you were trying, if it is reproducible ...
> Line numbers don't make much sense if you don't know where to exactly 
> look ... ;-)
> 

Klaus is right - I'd need to know at least the version of libqb being 
used, platform being used, does it happen every time you use that 
command? Also check that /dev/shm is not full.

I don't know what the pmxcfs command does, so it might also be worth 
looping in the proxmox team so they can help diagnose the issue.

Chrissie

**Comment by chrissie-c** [comment]
version 0.16 is libqb is very very old. the current version is 2.0.6

**Comment by Fabian-Gruenbichler** [comment]
I am not sure how pmxcfs got pulled in here - at least I see no indication in the back trace that this is somehow related to pmxcfs/PVE (and obviously, none of our supported releases use a libqb that is that ancient either..)

**Comment by chrissie-c** [comment]
I think we need to know what you are doing here then. I don't recognise the IPC name svtp, so it's not part of the clustering stack that we ship.

**Comment by jfriesse** [comment]
If my memory doesn't fool me is known - and fixed bug. SIGBUS is sent because libqb is trying to access position outside of backing file.(so for example backing file is 1M and libqb tries to access position 1M+1byte). No matter what, use new version of libqb.

**Comment by ddzrc** [comment]
it was /dev/shm have use by other proccess
