### ISSUE TITLE
gnu/lib-names.h header is glibc-specific and doesn't exist on musl systems

### ISSUE THREAD

**Issue by ptrcnull** [ClusterLabs/libqb#477]
as in the title; `#include <gnu/lib-names.h>` in tests/libstat_wrapper.c should be guarded by an additional `defined(__GLIBC__)`

**Comment by chrissie-c** [comment]
I imagine it will need more than that TBH. If you're not running glibc then the symbols that are overridden might be wrong too. I think the best thing in that circumstance is just to not run that test. We don't have a musl system in our CI to check against AFAIK.

**Comment by chrissie-c** [comment]
Closing this as that include has now been removed
