### ISSUE TITLE
resources.test is failed on SLES

### ISSUE THREAD

**Issue by safa003** [ClusterLabs/libqb#484]
Hi,
Im facing an error on SLES(x86_64) while creating rpms.Im trying to rebuild the source rpms for libqb package in SLES.I have edited the libqb.spec file and trying to rebuild the source rpm using the command `rpmbuild -ba libqb.spec` .While running this command,i faced an error where `resource.test` was getting failed.The libqb package version which I used was 
`libqb-2.0.6+20220323.758044b-150400.181.3.src.rpm`. 
I investigated the resource.log file and what I found was :

```
Error: dlock shared memory segments not closed/unlinked


Error: shared memory segments not closed/unlinked


Error: unexpected number of empty leftovers
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-event-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-event-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-response-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-response-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-request-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-request-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header

FAIL resources.test (exit status: 1)

```
Passed Test while running rebuilding the src rpm was :
1. start.test
2. array.test
3. map.test
4. rb.test
5. list.test
6. log.test
7. blackbox-segfault.sh
8. loop.test
9. ipc.test
10. ipc_sock.test

Information in `test-suite.log`:

```
`========================================================
   libqb 2.0.6+20220323.758044b: tests/test-suite.log
========================================================

# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: resources
===============


Error: dlock shared memory segments not closed/unlinked


Error: shared memory segments not closed/unlinked


Error: unexpected number of empty leftovers
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-event-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-event-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-response-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-response-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-request-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data
/dev/shm/qb-14091-14089-8-UQOZ2E/qb-request-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header

FAIL resources.test (exit status: 1)
`
```

Can you please help me to resolve this issue as I'm facing this issue while using the latest version of libqb package?

**Comment by chrissie-c** [comment]
On 19/05/2023 12:53, safa003 wrote:
> Hi,
> Im facing an error on SLES(x86_64) while creating rpms.Im trying to 
> rebuild the source rpms for libqb package in SLES.I have edited the 
> libqb.spec file and trying to rebuild the source rpm using the command 
> |rpmbuild -ba libqb.spec| .While running this command,i faced an error 
> where |resource.test| was getting failed.The libqb package version which 
> I used was
> |libqb-2.0.6+20220323.758044b-150400.181.3.src.rpm|.
> I investigated the resource.log file and what I found was :
> 
> |Error: dlock shared memory segments not closed/unlinked Error: shared 
> memory segments not closed/unlinked Error: unexpected number of empty 
> leftovers 
> /dev/shm/qb-14091-14089-8-UQOZ2E/qb-event-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data /dev/shm/qb-14091-14089-8-UQOZ2E/qb-event-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header /dev/shm/qb-14091-14089-8-UQOZ2E/qb-response-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data /dev/shm/qb-14091-14089-8-UQOZ2E/qb-response-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header /dev/shm/qb-14091-14089-8-UQOZ2E/qb-request-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-data /dev/shm/qb-14091-14089-8-UQOZ2E/qb-request-test_ipcc_truncate_when_unlink_fails_shm_fn13071-1684413230-header FAIL resources.test (exit status: 1) |
> 

Hi,

Can you try this patch please? It's upstream but not been rolled into a 
release yet. If it fixes the problem then I'll release a 2.0.7. If not 
then it'll take some more investigation

https://github.com/ClusterLabs/libqb/commit/0eb0991ad624a073203185592f15a3ca4ee4e68a?diff=unified

Chrissie

**Comment by chrissie-c** [comment]
That's strange, there's nothing that needs changing in the spec file for 
those tests.  If the failures are getting in the way of building RPMs 
then you could disable the tests temporarily, of course.

I haven't seen any resources.test failures on libqb since that patch 
(not on our CI systems - which include SuSE - anyway), so I'd intrigued 
to know more about your environment - kernel version, libc version, how 
/var/run is mounted, filesystem types, would be a good start.

Also, is it possible to try a build using the upstream source packages? 
I don't know what's in the SLES source RPMs so there might be something 
in there that's conflicting with my changes. Just downloading the latest 
git version and doing a "make check" would be enough. If that works then 
it's possibly something in the SLES sources. If not then it must be 
upstream.


Thanks
Chrissie

**Comment by chrissie-c** [comment]
I should add that it's most like that the failure is down to flaws in the tests, not the library - 99% of the time with those tests

**Comment by safa003** [comment]
Can you please tell me what can be done to resolve this problem?

**Comment by chrissie-c** [comment]
You could try the things I mentioned above, or get an SRPM from https://kronosnet.org/builds/libqb/opensuse-tumbleweed-x86-64/origin/main/latest/

**Comment by safa003** [comment]
I tried with the SRPM that you give.But still `resources.test `is getting failed.Is there any prerequisite that needs to be done?

**Comment by chrissie-c** [comment]
The only thing to really check before running is that /var/run is reasonably clean before starting. If it's nearly full then od things can happen.

**Comment by safa003** [comment]
I have checked `/var/run` and found that there were `test_ipc` files and `ipc_test` files. I removed those files and re-builded the SRPMS but still facing the same issue `FAIL: resources.test` .Is that the right way to do the cleaning part before rebuilding the SRPMS?

**Comment by chrissie-c** [comment]
One thing I have just noticed. If you run the tests with -j then the ipc & ipc_sock tests collide and can produce those errors. I haven't seen the SuSE RPM but if it uses -j then that might be it

**Comment by chrissie-c** [comment]
Also, I mean to ask you to  check /dev/shm as well as /var/run, sorry.

**Comment by safa003** [comment]
I have not used any -j in the commands.I ran the command like `rpmbuild -ba <SRPMs>` Also,i found some `qb` related files.I cleaned all that and then rebuilded the SRPMS but still I'm facing the same issue.

**Comment by chrissie-c** [comment]
Have you checked the srpm file? I don't know the contents of the SLES srpms

**Comment by safa003** [comment]
Srpm file contains test folder which contains all the tests required, then make files ,configure files,doxygen2man folder, version file, tools folder,libqb.spec.in file .I have checked the resource.test file if the patched code has got changed and yes it has got changed in it.Is there anyother changes I need to make in it to get it executed?

**Comment by safa003** [comment]
Srpm that I have used is `libqb-2.0.6.14-1.335d.src.rpm `from https://kronosnet.org/builds/libqb/opensuse-tumbleweed-x86-64/origin/main/latest/ . I have also tried `libqb-2.0.6+20220323.758044b-150400.181.3.src.rpm` and `libqb-2.0.6+20220323.758044b-lp154.180.1.src.rpm` from https://software.opensuse.org/download/package?package=libqb&project=home%3Ayan_gao%3Abranches%3Anetwork%3Aha-clustering%3AFactory%3ATest

**Comment by chrissie-c** [comment]
Can you post the whole build log somewhere please?

**Comment by chrissie-c** [comment]
I just downloaded that SRPM and tried building it. It uses 

/usr/bin/make -O -j8 V=1 VERBOSE=1

and make with -j is not supported on libqb, We're working on it at the moment but i's known to fail.

**Comment by chrissie-c** [comment]
You might like to try commit a3aedbc4192374f0b28b5ae460d2a4a94950264d - this fixes -j for all of our CI nodes so might help you.
