### ISSUE TITLE
libqb - pacemaker compatibility matrix

### ISSUE THREAD

**Issue by KuasarCloud** [ClusterLabs/libqb#501]
Hi, 

I am currently facing the issue described in https://github.com/ClusterLabs/libqb/pull/453. We are planning to upgrade libqb to version 2.0.6, but I am managing Pacemaker version 2.1.2 and am unsure how to verify its compatibility with the updated libqb version. Any guidance would be appreciated.

Regards

Ricardo P

**Comment by chrissie-c** [comment]
You don't say what version of libqb you are running. if it's version 2.anything then it will all be fine. If you are using libqb 1 then you will need to upgrade libqb and pacemaker together.

Generally we recommend to upgrade using distributors packages where available.

**Comment by kgaillot** [comment]
Pacemaker's `INSTALL.md` file lists the minimum versions of all dependencies. Pacemaker 2.1.2 is happy with libqb 0.17.0 or later. If you're upgrading from libqb <2.0.0, Pacemaker will need to be recompiled to accommodate incompatible changes.
