### ISSUE TITLE
error make rpm

### ISSUE THREAD

**Issue by greenx** [ClusterLabs/libqb#67]
I try build rpm package and get a error.
`"error: bad data in %changelog: Чт май 02 2013 ......"`
I have translated the text of this error, because it in Russian.
I see SPEC file.

```shell
%changelog
* @date@ Autotools generated version <nobody@nowhere.org> - @version@-1-@numcomm@.@alphatag@.@dirty@
- Autotools generated version
```
@date@ - also returns the date in Russian.
And it's not like rpmbuild.

After `export LANG=C` - build package complit.

**Comment by chrissie-c** [comment]
Now fixed in this commit:

2dd75dee249d8c112eda05e50082adda8a8e26e0

**Comment by greenx** [comment]
Life is lived not in vain :D

**Comment by chrissie-c** [comment]
haha. Sorry for the wait. We get there in the end.
